name=ESP Async TCP
version=2.1.0
includes=ESPAsyncTCP.h
author=ESP32Async, Dhimas Ardinata, Alex Bratchik
maintainer=Alex Bratchik <abratchik@gmail.com>
sentence=Async TCP Library for ESP8266 with SSL support.
paragraph=A fork of the original library modified to include a BearSSL implementation for robust SSL/TLS connections on the ESP8266.
category=Communication
url=https://github.com/abratchik/ESPAsyncTCP
architectures=espressif8266